services:
  mongodb:
    image: "mongo:7.0-jammy"
    env_file: ".env"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "$MONGODB_USER"
      MONGO_INITDB_ROOT_PASSWORD: "$MONGODB_PASSWORD"
    deploy:
      resources:
        limits:
          memory: "${MONGODB_MEMORY_LIMIT:-1G}"
        reservations:
          memory: "${MONGODB_MEMORY_RESERVATIONS:-1G}"
    command: ["--port", "${MONGODB_PORT:-27017}"]
    restart: "unless-stopped"

  api:
    build:
      context: "./api"
    env_file: ".env"
    environment:
      RPC_URI: "${API_RPC_URI:-http://localhost:3030}"
    restart: "unless-stopped"

  nginx:
    image: "nginx:1-alpine"
    ports:
      - "${NGINX_PORT:-44440}:${NGINX_LISTEN_PORT:-80}"
    env_file: ".env"
    environment:
      LISTEN_PORT: "${NGINX_LISTEN_PORT:-80}"
      PROXY_PASS: "${NGINX_PROXY_PASS:-http://api:3030}"
    volumes:
      - "./nginx/templates:/etc/nginx/templates"
    depends_on:
      - "api"
    restart: "unless-stopped"